Repository ZuluSCSI/ZuluSCSI-firmware, pull requests merged in 2022-09, with the labels that each got.

#57 Initial implementation of synchronous mode for RP2040
  lib/ZuluSCSI_platform_RP2040/ZuluSCSI_platform.h
  lib/ZuluSCSI_platform_RP2040/rp2040_sdio.cpp
  lib/ZuluSCSI_platform_RP2040/scsiPhy.cpp
  lib/ZuluSCSI_platform_RP2040/scsi_accel.pio
  lib/ZuluSCSI_platform_RP2040/scsi_accel.pio.h
  lib/ZuluSCSI_platform_RP2040/scsi_accel_rp2040.cpp
  lib/ZuluSCSI_platform_RP2040/scsi_accel_rp2040.h
Labels: enhancement

#58 Add device type autoconfiguration for more filename prefixes: MO, RE, TP
  README.md
  src/ZuluSCSI.cpp
  src/ZuluSCSI_disk.cpp
  src/ZuluSCSI_disk.h
Labels: bug, enhancement

#70 Rp2040 bugfixes
  lib/ZuluSCSI_platform_RP2040/scsi_accel_rp2040.cpp
  lib/ZuluSCSI_platform_RP2040/sd_card_sdio.cpp
  src/ZuluSCSI_disk.cpp
Labels: bug
